# Generated by Django 6.0.2 on 2026-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='hashed_password',
            field=models.CharField(max_length=100),
        ),
    ]
