# Generated by Django 6.0.2 on 2026-02-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_usermodel_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
