# Generated by Django 6.0.2 on 2026-02-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_taskmodel_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
